### ISSUE TITLE
Dropwizard plugin does not respect proxy's DNS TTL

### ISSUE THREAD

**Issue by knorby** [wavefrontHQ/java#147]
The dropwizard plugin seems to grab the address of the proxy only at startup and is neither respecting the TTL of the proxy's address (mentioning the TTL in specific as it is 15s in our case) or doing a fresh lookup on failures to send.

**Comment by moribellamy** [comment]
Thanks, I'll take a look :).

Are you referring to one of these libs: https://github.com/wavefrontHQ/java/tree/master/dropwizard-metrics? If so, are you using 3.1 or 4.0? I bet it's an issue in com.wavefront.integrations.Wavefront though, so it would affect both.

**Comment by knorby** [comment]
Mori, yeah we are using 3.1, but I did poke around, and the issue seems to be in com.wavefront.integrations.Wavefront.

**Comment by moribellamy** [comment]
I pushed https://github.com/wavefrontHQ/java/tree/mori-socket as a first-cut. My current theory is that the current library will just continually throw IOExceptions if the socket is ever broken. That new branch will retry on a broken socket before throwing to the user.

Next week I will repro the issue to make sure this fix is sufficient, then I can submit/release.

**Comment by panghy** [comment]
@moribellamy can you comment on the status of this issue?

**Comment by moribellamy** [comment]
@panghy I finished testing in my local client. My PR https://github.com/wavefrontHQ/java/pull/164 uses a socket that will attempt to reconnect on failure. So after that PR, we might have this story:

1. User initializes connection to WF proxy with this library
1. The resulting socket is broken, because the proxy goes down, or some other issue
1. We are able to successfully reconnect after one try (if DNS has been updated by now, this will be honored)

My PR isn't good enough to definitively close this issue though:

1. If DNS changes, but the original socket isn't broken, I think we will continue reporting through the old socket
1. We still throw an exception to the user if a single reconnect will not do the trick. This may or may not be ideal behavior (you could imagine a parametrized retry loop)

**Comment by panghy** [comment]
1. That's a tough one to solve, typically you would have a TTL on the socket but DNS changes should be rare within a local network and there are ways around it (VIPs, TCP load balancers, etc.). Resolving on failure should be good enough.
2. I think we should try to recover (instead of stuck failing) but throw if we can't recover (the user has to handle that case anyways).
